language: ruby

branches:
  only:
    - master

sudo: required

services:
  - docker

cache:
  directories:
    - test/fixtures/cookbooks/clamav_test/files

env:
  - CVD_PATH=test/fixtures/cookbooks/clamav_test/files

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development

before_script:
  - mkdir -p $CVD_PATH
  - "[ -e $CVD_PATH/main.cvd ] || wget -P $CVD_PATH http://database.clamav.net/main.cvd"
  - "[ -e $CVD_PATH/daily.cvd ] || wget -P $CVD_PATH http://database.clamav.net/daily.cvd"
  - "[ -e $CVD_PATH/bytecode.cvd ] || wget -P $CVD_PATH http://database.clamav.net/bytecode.cvd"

script:
  - chef exec rake && chef exec kitchen test
