language: ruby

gemfile:
  - Gemfile

rvm:
#  - 1.9.2
  - 1.9.3

env:
#  - CHEF_VERSION=10.14.4
  - CHEF_VERSION=10.16.6

script: "bundle exec rake; bundle exec rake converge"

# vim: ai et ts=2 sts=2 sw=2 ft=ruby fdm=marker
